### ISSUE TITLE
Launguage selection

### ISSUE THREAD

**Issue by IaintF** [mame82/duck2spark#5]
Hi! This isn't really an issue but i didn't find a way to contact you otherwise! When you said in your case (DE) what do i have to put in there for a Slovenian layout. SLV, SL, SLO doesn't work... Thanks!

**Comment by mame82** [comment]
I guess `si`
[See here](https://github.com/hak5darren/USB-Rubber-Ducky/blob/master/Encoder/resources/si.properties)

**Comment by IaintF** [comment]
Didn't work, had to download the source code

**Comment by IaintF** [comment]
Ok it works now, i downloaded the source code and copied the path of si.prop to cmd, but now there is another problem when executing: duck2spark.py -i raw.bin -l 1 -f 2000 -o sketch.ino

This is the error:


C:\Users\idk\Desktop\duck2spark-master\duckencoder.py-master>duck2spark.py -i ra
w.bin -l 1 -f 2000 -o sketch.ino
Press ENTER to exit
Traceback (most recent call last):
  File "C:\Users\idk\Desktop\duck2spark-master\duckencoder.py-master\duck2spark.
py", line 157, in <module>
    input('Press ENTER to exit')
  File "<string>", line 0
